# -*- coding: utf-8 -*-
"""python for generative AI btech CS DS 2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17yTWicsByOM3mp70FEkylCjaoT5k7qpT
"""

x = 1
type(x)

y = 0.0
type(y)

z = 3+4j
type(z)

#string---data in the form of text
a = "Solan"
type(a)

#boolean--it is used to store a values that is True and False
x = True
type(x)

y= False
type(y)

#None -- it is null value means nothing
e = None
type(e)

#addition
2+2

x = 4
y = 6
z = x+y
print(z)

#subtraction
a = 10
b = 5
c = a-b
print(c)

#multiplication
a = 5
b = 2
c = a*b
print(c)

#division
a = 10
b = 5
c = a/b
print(c)

#expontiation
a = 2
b = 3
c = a**b
print(c)

#floor division --return the result in whole number
7//2

7.0//2

#modulus -- the output is remainder
5%2

#single quotes string
my_sub = 'Machine learning'
type(my_sub)

#double quotes string
my_college = "Shoolini university"
type(my_college)

#triple quotes string
my_sentence = '''This sentence is multipline line,
this is also known as string'''
type(my_sentence)

#find the length of string
my_sub = "Machine learning"
len(my_sub)

my_sub[0]

my_sub[1]

my_sub[15]

my_sub = "Machine learning"
my_sub[-1]

my_sub[-9]

my_sub[0:7:1]

my_sub[0:7]#bydefault stepsize is 1

#lower()--this method used to convert string into lower case
my_sub = "PYTHON"
my_sub.lower()

#upper()--this method used to convert string into uppercase
my_sub = "python"
my_sub.upper()

#count()--this method count particular character in string
my_string = "Machine learning"
my_string.count('a')

my_list = [78, 89, 23, 45, 56]
type(my_list)

mixed_list = [23, 3.14, "apple", True, None]
type(mixed_list)

print(my_list)

#find the length of the list
len(my_list)

#positive indexing
my_list = [78,89,23,34,10]
print(my_list[0])
print(my_list[1])
print(my_list[2])
print(my_list[3])
print(my_list[4])

#negative indexing
my_list = [78,89,23,34,10]
print(my_list[-1])
print(my_list[-2])
print(my_list[-3])
print(my_list[-4])
print(my_list[-5])

my_list = [2, 3, 7, 1, 4, 5]
my_list[0:5:1]

#bydefault stepsize is one
my_list[0:5]

my_list[0:]

my_list[:5]

my_list[: : -1]

#function in list
#min()--return the minimum number of the list
my_list =[98, 34, 56, 45, 12]
min(my_list)

#max()--return maximum number of the list
max(my_list)

my_list

#sum()--return addition of the all item of the list
sum(my_list)

#sorted()--this function arrange list increasing or decreasing order
list1 = [9, 7, 12, 4, 8, 3]
sorted(list1, reverse = True)

list1

#append()--this method add item end of the list and take item as argument
my_list = [90, 87, 65, 34]
print(my_list)
my_list.append(100)
print(my_list)

my_list

my_list[2] = 200
print(my_list)

#extend()--this method merge a list into another list
list1 = [90, 78, 65]
list2 = [56, 89, 45]
list1.extend(list2)
print(list1)

#pop()--this method remove item from the list, take index as argument
my_list  = [78, 56, 34, 12]
my_list.pop()

#remove()--this method remove item of the list, take item as a argument
list1 = [90, 87, 65, 23]
list1.remove(87)
list1

#reverse()-- this method reverse the list
my_list = [90, 87, 56, 23]
my_list.reverse()
print(my_list)

#dictionary
my_dict = {"Name":"Amit", "College":"Shoolini university"}
type(my_dict)

print(my_dict)

print(my_dict["Name"])
print(my_dict["College"])

#method in dictionary
#keys()--this method find the keys of dictionary
list(my_dict.keys())

#values()--this method find value of the dictionary
list(my_dict.values())

#items()--this method find items of the dictionary
list(my_dict.items())

#get()--this method find value in the dictionary and key take as argument
my_dict.get("Name")

print(my_dict.get("Age", "Age is not present"))

#update()--this method update the dictionary and take dictionary as argument
my_dict.update({"Age":20})
print(my_dict)

my_dict.update({"Name":"Jagat"})
print(my_dict)

#conditional satement
age = int(input("Enter your age:"))
if age>60:
  print("You are too old for marry")
elif age<18:
  print("You are too young for marry")
else:
  print("we will find perfact match for you")

my_sub = "Python"
 print(my_sub[0])
 print(my_sub[1])
 print(my_sub[2])
 print(my_sub[3])
 print(my_sub[4])
 print(my_sub[5])

my_sub = "python"
for i in my_sub:
  print(i)

for i in range(0, 6, 1):
  print(i)

for i in range(0, 6):
  print(i)

for i in range(6):
  print(i)

my_sub = "python"
for i in range(len(my_sub)):
  print(my_sub[i], "->", i)

#while loop
i = 0 #inilization
while i<5: #condition
  print(i)
  i+=1 #increment

#loops and control statement
#break -- this statement break the loop
i = 0
while i<5:
  i+=1 #increment
  if i==3:
    break
  else:
    print(i)

#continue statement-- this statement skip the current iteration
i = 0
while i<5:
  i+=1
  if i==3:
    continue
    print(i)
  else:
    print(i)

#pass statement -- this statement pass the code
i = 0
while i<5:
  i+=1
  if i==3:
    pass
    print(i)
  else:
    print(i)

#user defined function without argument
def add():
  a = int(input("Enter the first number: "))
  b = int(input("Enter the second number: "))
  return a+b

add()

#positional argument
def calculation(a, b):
  print("addition", a+b)
  print("subtraction", a-b)
  print("multiplication", a*b)
  print("Division", a/b)
  return "Calculation is complete"

print(calculation(10, 5))

#default argument
def area_perimeter(width=4, height=8):
  area = width*height
  perimeter = 2*(width + height)
  return "Area is", area, "and perimeter is", perimeter

print(area_perimeter(10, 20))

#keyword argument
def interest(p, r, t):
  i = (p*r*t)/100
  return i

print(interest(r = 10, t = 2, p = 1000))

#mixed argument
#positional argument follows keyword argument
print(interest(1000, t = 2, r = 10))

print(interest(r = 10,p=1000,  2))

#variable length argument
#non keyword positional variable length argument
def test(*args):
  print(args)
  print(len(args))
  print(type(args))

test(2,3, 4, 8, 9, 7)

def sum_number(*args):
  sum = 0
  for num in args:
    sum+=num
  return sum

sum_number(3, 5, 6, 7, 8, 9)

#keyword variable length argument
def test(**kwargs):
  print(kwargs)
  print(type(kwargs))
  print(len(kwargs))

test(a = 10, b = 20, c = 30)

def pass_students(**kwargs):
  pass_student_list = []
  for name, marks in kwargs.items():
    if marks>35:
      pass_student_list.append(name)
  return pass_student_list

pass_students(A = 30, B = 40, C = 50, D= 80, E = 20)

import numpy as np

#one dimensional array
oned_array = np.array([1, 2,3, 4])
print(oned_array)

import numpy as np

#one dimensional array
oned_array = np.array([1, 2, 3])
print(oned_array)

#two dimensional array
twod_array = np.array([[1, 2, 3], [4, 5, 6]])
print(twod_array)

#row vector
row_vector = np.array([[1, 2, 3]])
print(row_vector)

column_vector = np.array([[1], [2], [3]])
print(column_vector)

column_vector = row_vector.transpose()
print(column_vector)

#ndim -- find the dimension of vector
column_vector.ndim

#size--find the number of item
column_vector.size

print(column_vector)

#shape
column_vector.shape

print(row_vector)

row_vector.shape

twod_array = np.array([[1, 2, 3], [4, 5, 6]])
print(twod_array)

print(twod_array[0][1])

print(twod_array[1][2])

print(twod_array[0,1])

print(twod_array[0:2,0:2])

threed_array = np.random.randint(1, 10, (3, 3))
print(threed_array)

print(threed_array[0:2, 0:2 ])

import numpy as np
mat1 = np.matrix("1, 2, 3; 4, 5, 6; 7, 8, 9")
print(mat1)

mat2 = np.matrix([[1, 2, 3],[4, 5, 6]])
print(mat2)

mat3 = np.random.random((3, 3))
print(mat3)

mat4 = np.random.randint(1, 20, (3, 3))
print(mat4)

zeros_array = np.zeros((3, 3), dtype = int)
print(zeros_array)

ones_array = np.ones(( 3, 3), dtype = int)
print(ones_array)

print(ones_array*100)

my_array = np.full((3, 3), 10)
print(my_array)

my_array = np.array([1, 2,3, 4])
print(my_array)

power_array = np.power(my_array, 2)
print(power_array)

print(my_array)

exp_array = np.exp(my_array)
print(exp_array)

log_array = np.log(my_array)
print(log_array)

log2_array = np.log2(my_array)
print(log2_array)

log10_array = np.log10(my_array)
print(log10_array)

a = np.random.randint(1, 10, (2, 3))
b = np.random.randint(1, 10, (3,2))
print(a)
print(b)

print(np.dot(a, b))

import matplotlib.pyplot as plt
import numpy as np

xpoint = np.array([1,3])
ypoint = np.array([2, 4])
plt.plot(xpoint,ypoint)
plt.show()

cgpa = np.array([6,6.5,7,7.8, 8, 8.4, 9, 9.7, 10])
package = np.array([5, 5.4, 6, 6.2, 6.8, 7, 7.5, 8, 8.8])
plt.plot(cgpa,package,"*:g", ms = 15,mec="orange",linewidth =5)
font1 ={"family":"serif", "color":"blue", "size":15}
font2 ={"family":"serif", "color":"Red", "size":20}
plt.title("Shoolini university students data", fontdict = font2)
plt.xlabel("CGPA",fontdict = font1)
plt.ylabel("PACKAGE",fontdict = font1)
#plt.title("Shoolini university students data")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
fruit = np.array(["Apple", "Banana", "Orange", "Watermelon"])
quantity = np.array([100, 120, 80, 50])
color = np.array(["red", "yellow", "orange", "green"])
plt.bar(fruit, quantity, color = color)
plt.xlabel("Fruit")
plt.ylabel("Quantity")
plt.title("Fruit Quantity")
plt.show()

fruit = np.array(["Apple", "Banana", "Orange", "Watermelon"])
quantity = np.array([100, 120, 80, 50])
color = np.array(["red", "yellow", "orange", "green"])
plt.barh(fruit, quantity, color = color)
plt.xlabel("Quantity")
plt.ylabel("Fruit")
plt.title("Fruit Quantity")
plt.show()

#pie plot
quantity = np.array([20, 35, 15, 30])
fruit = np.array(["Apple", "Banana", "Orange", "Mango"])
myexplode = [0.2, 0, 0, 0]
plt.pie(quantity, labels = fruit, explode = myexplode)
plt.legend(title = "Fruit",loc = "best")
plt.show()

#scatter plot
age_of_car = np.array([4, 6, 8, 10, 12, 14, 16, 18])
speed_of_car = np.array([150, 130, 120, 110, 100, 90, 80, 70])
plt.scatter(age_of_car, speed_of_car)
plt.xlabel("Age of car")
plt.ylabel("Speed of car")
plt.title("Age and speed of car")
plt.show()

#histogram-- it shows frequency distribution
import numpy as np
x = np.random.randint(40, 100, (1, 200))
print(x)
x = x.flatten()
print(x)

plt.hist(x,bins = 20)
plt.show()

import pandas as pd

#Series--one dimensional data structure of pandas
my_series = pd.Series(["Appple", "Banana", "Mango", "Orange"], name= "Fruit" )
my_series

#DataFrame--two dimensional data structure of pandas
list_into_list = [["Amar",15],["Akbar",14], ["Anthony",13]]
df = pd.DataFrame(list_into_list, columns = ["Name", "Age"])
df

#how to read csv file
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/data/imdb_data.csv")
df

#head()--bring rows(data point) from top of the dataframe
df.head(100)

#tail()--bring the rows(data point) from bottom of the data frame
df.tail(10)

#find the number of rows and column in the data frame
df.shape

#find the name of the all columns
df.columns

#bring the rows(data point) randomly from the data
df.sample(5)

#find the information of the data
df.info()

#how does the data looklike mathematically
df.describe()

#find the duplicate value
print(df.duplicated().sum())

#find the null value
df.isnull().sum()

df.columns

#slicing and indexing
#find the single column with all row
df["title"]

#multiple column with all rows
df[["title","budget", "revenue", 'original_language']]

#slicing with help of rows
df[0:4]

#find the some number of rows and columns
df.iloc[0:4, 0:3]

df.loc[0:4, ["title", "budget","revenue"]]

#find the unique value in particular column
df["original_language"].unique()

english_movie = df[df["original_language"] == "en"]
english_movie

#how to write file in csv format
english_movie.to_csv("english_movie.csv")

