# -*- coding: utf-8 -*-
"""python for generative AI btech others

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oOIF7K8_YTNW4uaMVf7tMysEpdGMLfFH
"""

x = 10

x

mysub = "python"
mysub

_mycity = "Solan"
_mycity

my_city1 = "Shimla"
my_city1

2mycity = "New delhi"
2mycity

import keyword
print(keyword.kwlist)

x = 1
type(x)

y = 0.0
type(y)

z = 3+4j
type(z)

x = "solan"
type(x)

a = True
type(a)

b = False
type(b)

e = None
type(e)

#single quotes
 my_sub = 'Generative AI'
 type(my_sub)

#double quotes
my_college = "Shoolini University"
type(my_college)

#triple quotes
my_sentence = '''this sentence is used for multiple
lines, this is also string'''
type(my_sentence)

my_sub = "Machine learning"
len(my_sub)

my_sub = "Machine learning"
my_sub[0]

my_sub[-16]

my_sub[6]

my_sub = "Machine learning"
my_sub[0:7]

my_sub[8::1]

my_sub = "Machine learning"
my_sub[0:15:2]

my_sub = "Machine learning"
my_sub[-1::-1]

my_sub = "PYTHON"
my_sub.lower()

#upper()--this method convert string into uppercase
my_string = "Machine learning"
my_string.upper()

#count() -- this method count the number of character
my_string = "Machine learning"
my_string.count('e')

my_list = [78, 89, "apple", 3.14]
type(my_list)

fruit_list = ["apple", "banana", "cherry"]
type(fruit_list)

my_list = [78, 89, "apple", 3.14]
len(my_list)

print(my_list)

my_list = [78, 89, 23, 75, 22]
my_list[0]

my_list[-1]

my_list = [78, 89, 23, 24, 50]
print(my_list[0:4:1])
print(my_list[0:4])

print(my_list[0:])

my_list[: :-1]

list1 = [7, 8, 5, 4, 2]
min(list1)

#max()--this function find maximum number of the list
max(list1)

#sum()--this function return addition of the item
sum(list1)

#sorted()--this function arrange list in increasing or decreasing order
my_list = [89, 90, 56, 34, 100, 45]
sorted(my_list, reverse = True)

my_list

#append()--this method add the item end of the list
list1 = [89, 76, 56]
list1.append(100)
list1

#extend()--this method used to merge list into another list
list1 = [12, 34,56,89]
list2 = [11,23,56]
list1.extend(list2)
list1

#sort()--this method arrange list in increasing or decreasing order
my_list = [67, 45, 12, 34]
my_list.sort(reverse = True)
my_list

#pop()--this method remove item from the list,and take index as argument
list1 = [90, 78, 45, 23, 96]
list1.pop(1)

#reverse()--this method used to reverse the list
my_list = [90, 78, 65, 100]
my_list.reverse()
my_list

age = int(input("Enter your age: "))
if age>60:
  print("you are too old for marry")
elif age<18:
  print("you are too young for marry")
else:
  print("we will find perfect match for you")

#loop helps to execute block of code repeatedly
 my_sub = "python"
 print(my_sub[0])
 print(my_sub[1])
 print(my_sub[2])
 print(my_sub[3])
 print(my_sub[4])
 print(my_sub[5])

my_sub = "Python"
for i in my_sub:
  print(i)

my_list = [90, 78, 45, 23]
for i in my_list:
  print(i)

for i in range(0, 6, 1):
  print(i)

for i in range(0,6):
  print(i)

for i in range(6):
  print(i)

#while
i = 0 #initialization
while i<5:
  print(i)
  i+=1

#break--this statement break the loop
i = 0
while i<5:
  i+=1
  if i == 3:
    break
  else:
    print(i)

#continue statement--skip the current iteration
i = 0
while i<5:
  i+=1
  if i == 3:
    continue
    print(i)
  else:
    print(i)

#pass statement---pass the code
i = 0
while i<5:
  i+=1
  if i==3:
    pass
    print(i)
  else:
    print(i)

#user defined function without argument
def add():
  a = int(input("Enter first number: "))
  b = int(input("Enter second number: "))
  return a+b

print(add())

#positional argument
def Calculation(a, b):
  print("addition", a+b)
  print("Subtraction", a-b)
  print("Multiplication", a*b)
  print("division", a/b)

Calculation(10, 5)

#default argument
def area_perimeter(width = 4, height = 8):
  area = width*height
  perimeter = 2*(width+height)
  return "Area is", area, "and perimeter is ", perimeter

area_perimeter(10, 20)

#keyword argument
def interest(p, r, t):
  i = (p*r*t)/100
  return i

interest(r = 10, t = 2, p =1000)

#mixed argument
interest(1000, t = 2, r = 10)

interest(p = 1000, r = 10, 2)

import numpy as np
twod_array = np.array([[1, 2,3],[4,5, 6],[7,8,9]])
print(twod_array)

print(twod_array[0][1])

print(twod_array[1][2])

#slicing
print(twod_array)

print(twod_array[0:2,0:2])

mat1 = np.matrix("1, 2,3;4, 5, 6;7,8,9")
print(mat1)

zeros_array = np.zeros((3, 3),dtype = int)
print(zeros_array)

ones_array = np.ones((3,3),dtype = int)
print(ones_array)

print(ones_array*99)

my_array = np.full((3, 3), 100)
print(my_array)

random_array = np.random.random((3, 3))
print(random_array)

randint_array = np.random.randint(1, 20,(3,3))
print(randint_array)

import numpy as np
my_array = np.array([1, 2,3,4])
print(my_array)
power_array = np.power(my_array, 2)
print(power_array)

log_array = np.log(my_array)
print(log_array)

log2_array = np.log2(my_array)
print(log2_array)

log10_array = np.log10(my_array)
print(log10_array)

import matplotlib.pyplot as plt
import numpy as np

xpoint = np.array([1,3])
ypoint = np.array([2,4])
plt.plot(xpoint,ypoint)
plt.show()

cgpa = np.array([6,7,8,9,10])
package = np.array([5, 6, 7, 9, 12])
plt.plot(cgpa, package,"*:g",ms=15, mec = "orange",linewidth = 5)
plt.xlabel("CGPA")
plt.ylabel("Packge(LPA)")
plt.title("Shoolini university students data")
plt.show()

#bar plot--it is work on numerical as well as categorical data
import matplotlib.pyplot as plt
import numpy as np
fruit = np.array(["Apple", "Banana", "Orange", "Watermelon"])
quantity = np.array([100, 120, 90, 80])
color = np.array(["red", "yellow", "orange", "green"])
plt.bar(fruit, quantity, color = color)
plt.show()

fruit = np.array(["Apple", "Banana", "Orange", "Watermelon"])
quantity = np.array([100, 120, 90, 80])
color = np.array(["red", "yellow", "orange", "green"])
plt.barh(fruit, quantity, color = color)
plt.show()

#pie plot
fruit_percentage = np.array([20, 25, 35, 20])
fruit_name = np.array(["Apple", "Banana", "Orange", "Watermelon"])
colors = np.array(["red", "yellow", "orange", "green"])
myexplode = np.array([0.2, 0, 0, 0])
plt.pie(fruit_percentage, labels = fruit_name, autopct="%1.1f%%",
        colors =colors, explode = myexplode  )
plt.legend(title = "Fruit", loc = "best")
plt.show()

age_of_car = np.array([4,5, 6, 7, 8, 9, 10, 11, 12])
speed_of_car = np.array([150, 140, 130, 120, 110, 100, 90, 80, 70])
plt.scatter(age_of_car, speed_of_car, color = "red")
plt.xlabel("Age of car")
plt.ylabel("Speed of car")
plt.title("Age vs speed of car")
plt.show()

#histogram--it showing the frequency distribution of the data
import numpy as np
x = np.random.randint(40, 100, (1, 200))
x = x.flatten()
print(x)

plt.hist(x, bins = 20)
plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.title("Marks distribution")
plt.show()

import pandas as pd

fruit_list = ["apple", "banana", "cherry"]
my_series = pd.Series(fruit_list, name = "Fruits")
my_series

list_of_list = [["apple", 100],["Banana", 120],["orange",150]]
df = pd.DataFrame(list_of_list, columns = ["Fruit", "Quantity"])
df

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/data/imdb_data.csv")
df

#find the number of rows and column
df.shape

#bring the number of rows from top of the dataframe
df.head(100)

#bring the data from bottom of the dataframe
df.tail(10)

#bring the rows from the dataframe randomly
df.sample(10)

#find the information of the data
df.info()

#how does the data looklike mathematically
df.describe()

